version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:5000/api}
    ports:
      - "${DOCKER_FRONTEND_PORT:-3000}:80"
    volumes:
      - ./packages/frontend/src:/app/frontend/src
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "${DOCKER_BACKEND_PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./packages/backend/src:/app/backend/src
      - ./config:/app/backend/config
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - "${DOCKER_MONGO_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
